### ISSUE TITLE
Clone to Netlify fails: jekyll-default-layout

### ISSUE THREAD

**Issue by kylegrover** [daviddarnes/alembic-netlifycms-kit#3]
Tried the 'Deploy to Netlify' button a few times, on Gitlab and on Github in case that made any difference (it didn't). Error message from Netlify deploy log:

> Dependency Error: Yikes! It looks like you don't have jekyll-default-layout or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. If you've run Jekyll with `bundle exec`, ensure that you have included the jekyll-default-layout gem in your Gemfile as well. The full error message from Ruby is: 'cannot load such file -- jekyll-default-layout'

**Comment by kylegrover** [comment]
I do see jekyll-default-layout in https://github.com/daviddarnes/alembic-netlifycms-kit/blob/master/_config.yml so I have no idea what's going on here. slightly more info from the deploy log in case it's helpful

```
11:54:45 PM: $ jekyll build
11:54:45 PM: Configuration file: /opt/build/repo/_config.yml
11:54:46 PM:   Dependency Error: Yikes! It looks like you don't have jekyll-default-layout ...
```

**Comment by daviddarnes** [comment]
Oops sorry about that @kylegrover! The latest version of Alembic no longer needs this plugin, but I forgot to remove it from the config so it was looking for a plugin that no longer exists. I've just pushed a fix if you don't mind testing 😁

**Comment by kylegrover** [comment]
Awesome, that fixed it! Thanks for the quick response
